### ISSUE TITLE
python3 generate.py not responding

### ISSUE THREAD

**Issue by C-Fu** [gelerum/nft-collection-generator#1]
No errors, no nothing, it just hangs... unless I Ctrl + C, in which case this happens
```
~/nft-collection-generator# python3 generate.py
^CTraceback (most recent call last):
  File "generate.py", line 107, in <module>
    main()
  File "generate.py", line 77, in main
    new_image = generate_image(data)
  File "generate.py", line 16, in generate_image
    image[layer] = random.choices([x["name"] for x in data[layer]], [
  File "generate.py", line 16, in <listcomp>
    image[layer] = random.choices([x["name"] for x in data[layer]], [
KeyboardInterrupt
```

I have 3 layers - main, border, motif. filenames are main (1).png... main (16).png, border (1).png ... border (8).png, motif (1).png ... motif (6).png. weights for main, border and motif are 100 each in total.

```
{
    "main": [
        {
            "name": "main",
            "fileName": "main (1).png",
            "weight": 6
        },
.
.
.
        {
            "name": "main",
            "fileName": "main (16).png",
            "weight": 7
        },
    ],
    "border": [
        {
            "name": "border",
            "fileName": "border (1).png",
            "weight": 12
        },
.
.
.
        {
            "name": "border",
            "fileName": "border (8).png",
            "weight": 13
        },
    ],
   "motif": [
        {
            "name": "motif",
            "fileName": "motif (1).png",
            "weight": 16
        },
.
.
.
        {
            "name": "motif",
            "fileName": "motif (6).png",
            "weight": 17
        },
    ]
}
```

And .env is 
```
URL_TO_IMAGE=test_col1
NEW_URL_TO_IMAGE=new_test_col1

COLLECTION_SIZE=768
NAME=test_col1
PATH_TO_JSON=./layers.json
PATH_TO_LAYERS=./layers
PATH_TO_IMAGES=./images
PATH_TO_METADATA=./metadata

PATH_TO_RESIZED_IMAGES=./images-resized
OUTPUT_IMAGE_SIZE_X=576
OUTPUT_IMAGE_SIZE_Y=576
```
Images are 491x93 px, around 90kb to 400kb in size. Even renaming all to main_10.png doesn't work.
Where did I do wrong?

Thanks a lot!

**Comment by gelerum** [comment]
> {
>             "name": "border",
>             "fileName": "border (1).png",
>             "weight": 12
>         },
> .
> .
> .
>         {
>             "name": "border",
>             "fileName": "border (8).png",
>             "weight": 13
>         },

I gonna do some tests. Error may be because you use similar names for items of same layer. Or because you use images with size 491 x 93, but output file is 576 x 576

**Comment by gelerum** [comment]
**Anyway you must use different names in `"name"` for every item of layer.** It is logic of my code. If you use equal names your output images will use same item of layer. All ouput images will use one file "border (1).png".
Try above first, if it doesn't work for you contact me in telegram to send me your layers.json, .env and images
